// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RCA_StudyManagementSystem.Data;

#nullable disable

namespace RCA_StudyManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306160616_AppInit")]
    partial class AppInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RCAContactReimbursementEntity", b =>
                {
                    b.Property<Guid>("RCAContactsRCAContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReimbursementEntitiesReimbursementEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RCAContactsRCAContactId", "ReimbursementEntitiesReimbursementEntityId");

                    b.HasIndex("ReimbursementEntitiesReimbursementEntityId");

                    b.ToTable("RCAContactReimbursementEntity");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Batch", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumberOfCases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BatchId");

                    b.ToTable("Batch");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.DailyPathSubmission", b =>
                {
                    b.Property<Guid>("DailyPathSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DailyPathSubmissionId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("StudyId");

                    b.ToTable("DailyPathSubmission");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.DoNotContact", b =>
                {
                    b.Property<Guid>("DoNotContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateLastContact")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialSecurityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoNotContactId");

                    b.ToTable("DoNotContact");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Doctor", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuplicateOfDoctorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPathologist")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MigratedDoctorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimarySpecialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondarySpecialty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Histology", b =>
                {
                    b.Property<Guid>("HistologyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HistologyBehavior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("HistologyId");

                    b.ToTable("Histology");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Hospital", b =>
                {
                    b.Property<Guid>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuplicateOfHospitalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("bit");

                    b.Property<string>("MigratedHospitalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReimbursementEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalId");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateEmailed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReminderSent")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSignedInvoiceReturned")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceQuarter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RASRCompleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RASRId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RASRSubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReimbursementEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("DECIMAL(19, 2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ReimbursementEntityId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.InvoiceItem", b =>
                {
                    b.Property<Guid>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("NumPathReports")
                        .HasColumnType("int");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InvoiceItemId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("StudyId");

                    b.ToTable("InvoiceItem");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Lookup", b =>
                {
                    b.Property<Guid>("LookupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LookupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LookupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LookupType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParentCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("LookupId");

                    b.ToTable("Lookup");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.PathReport", b =>
                {
                    b.Property<Guid>("PathReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ALNL_NodesExamined")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALNL_NodesExamined2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALNL_PositiveNodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALNL_PositiveNodes2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgeAtProcedure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizingProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizingProvider2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizingProviderComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizingProviderComments2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfProcedure")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DoNotInvoice")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Doctor2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DxAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DxAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DxCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DxCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DxCountyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DxPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DxState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DxZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExportStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GleasonSum1")
                        .HasColumnType("int");

                    b.Property<int?>("GleasonSum2")
                        .HasColumnType("int");

                    b.Property<string>("HistologicDiff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologicDiff2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologicGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologicGrade2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologyBehavior1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologyBehavior2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologyCode1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologyCode2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologyDiagnosis1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologyDiagnosis2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologyDiagnosisComments1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologyDiagnosisComments2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospAddress1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospFaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HospitalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAddendum")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnHold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOutsidePathReport")
                        .HasColumnType("bit");

                    b.Property<string>("MD2Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MD2Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MD2Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MD2City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MD2County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MD2Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MD2FaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MD2PhoneNumber1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MD2PhoneNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MD2State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MD2ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDAddress3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDFaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDPhoneNumber1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDPhoneNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarginStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarginStatus2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MigratedCCRNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("NumCoresBiopsy")
                        .HasColumnType("int");

                    b.Property<int?>("NumCoresCancer")
                        .HasColumnType("int");

                    b.Property<string>("OrigHospAddress1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigHospAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigHospCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigHospFaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigHospPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigHospState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigHospZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrigHospitalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginatingHospitalComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginatingHospitalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginatingHospitalPathReportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PSA_ng_ml")
                        .HasColumnType("float");

                    b.Property<string>("Path2Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path2Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path2Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path2City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path2County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path2Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path2FaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path2PhoneNumber1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path2PhoneNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path2State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path2ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathAddress3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathComments2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathFaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PathIndex")
                        .HasColumnType("int");

                    b.Property<string>("PathPhoneNumber1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathPhoneNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathProcedure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathProcedure2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PathReportObtained")
                        .HasColumnType("bit");

                    b.Property<string>("PathState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pathologist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pathologist2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Pathologist2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PathologistComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathologistComments2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PathologistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerineuralInvasion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrimGleason1")
                        .HasColumnType("int");

                    b.Property<int?>("PrimGleason2")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RcaExportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reimbursement1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reimbursement2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecGleason1")
                        .HasColumnType("int");

                    b.Property<int?>("SecGleason2")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteCode2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlidesResideAtSubmittingHospital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StudySubmission")
                        .HasColumnType("bit");

                    b.Property<string>("SubmittingHospital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmittingHospitalPathReportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("TumorSize")
                        .HasColumnType("float");

                    b.Property<double?>("TumorSize2")
                        .HasColumnType("float");

                    b.HasKey("PathReportId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SubmittingHospitalPathReportNumber")
                        .IsUnique();

                    b.ToTable("PathReport");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.PathReportExport", b =>
                {
                    b.Property<Guid>("PathReportExportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PathReportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PathReportExportId");

                    b.HasIndex("BatchId");

                    b.HasIndex("PathReportId");

                    b.ToTable("PathReportExport");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ethnicity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EthnicityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MigratedCCRNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialSecurityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Suffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("StudyId");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.PatientPhoneNumber", b =>
                {
                    b.Property<Guid>("PatientPhoneNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumberComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientPhoneNumberId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientPhoneNumber");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.PatientStatus", b =>
                {
                    b.Property<Guid>("PatientStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastContact")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InformedOfCancerDiagnosis")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("NoContact")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("StatedNoCancerDiagnosis")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PatientStatusId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StudyId");

                    b.ToTable("PatientStatus");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.RCAContact", b =>
                {
                    b.Property<Guid>("RCAContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Credentials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RCAContactId");

                    b.ToTable("RCAContact");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.ReimbursementEntity", b =>
                {
                    b.Property<Guid>("ReimbursementEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttentionTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoicePrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayableTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReimbursementEntityId");

                    b.ToTable("ReimbursementEntity");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.ReimbursementEntityRCAContact", b =>
                {
                    b.Property<Guid>("ReimbursementEntityRCAContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimaryContact")
                        .HasColumnType("bit");

                    b.Property<Guid>("RCAContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReimbursementEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReimbursementEntityRCAContactId");

                    b.HasIndex("RCAContactId");

                    b.HasIndex("ReimbursementEntityId");

                    b.ToTable("ReimbursementEntityRCAContact");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Study", b =>
                {
                    b.Property<Guid>("StudyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CCR_F14_ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ColorDark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorLight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Design")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEnrolledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaxAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMaxAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMaxNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMinAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrincipalInvestigator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudySite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudyId");

                    b.ToTable("Study");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.StudyContact", b =>
                {
                    b.Property<Guid>("StudyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfidentialAgreementSigned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExportEmailReceived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnTeamsChannel")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudyContactId");

                    b.HasIndex("StudyId");

                    b.ToTable("StudyContact");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.StudyHeader", b =>
                {
                    b.Property<Guid>("StudyHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExportTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudyHeaderId");

                    b.HasIndex("StudyId");

                    b.ToTable("StudyHeader");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.StudyHistology", b =>
                {
                    b.Property<Guid>("StudyHistologyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HistologyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudyHistologyId");

                    b.HasIndex("HistologyId");

                    b.HasIndex("StudyId");

                    b.ToTable("StudyHistology");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.StudyLookup", b =>
                {
                    b.Property<Guid>("StudyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("StudyLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudyId", "LookupId");

                    b.HasIndex("LookupId");

                    b.ToTable("StudyLookup");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.StudyReportHeader", b =>
                {
                    b.Property<Guid>("StudyReportHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExportTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudyReportHeaderId");

                    b.ToTable("StudyReportHeader");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RCA_StudyManagementSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RCAContactReimbursementEntity", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.RCAContact", null)
                        .WithMany()
                        .HasForeignKey("RCAContactsRCAContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.ReimbursementEntity", null)
                        .WithMany()
                        .HasForeignKey("ReimbursementEntitiesReimbursementEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.DailyPathSubmission", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Hospital", "Hospitals")
                        .WithMany("DailyPathSubmissions")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Study", "Studies")
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospitals");

                    b.Navigation("Studies");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Invoice", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.ReimbursementEntity", "ReimbursementEntity")
                        .WithMany()
                        .HasForeignKey("ReimbursementEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReimbursementEntity");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.InvoiceItem", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Invoice", null)
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Study", "Study")
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.PathReport", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Patient", "Patient")
                        .WithMany("PathReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.PathReportExport", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Batch", "Batch")
                        .WithMany("PathReportExports")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.PathReport", null)
                        .WithMany("PathReportExports")
                        .HasForeignKey("PathReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Patient", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Study", "Study")
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.PatientPhoneNumber", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Patient", "Patient")
                        .WithMany("PatientPhoneNumbers")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.PatientStatus", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Study", "Study")
                        .WithMany("PatientStatuses")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.ReimbursementEntityRCAContact", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.RCAContact", "RCAContact")
                        .WithMany("ReimbursementEntityRCAContacts")
                        .HasForeignKey("RCAContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.ReimbursementEntity", "ReimbursementEntity")
                        .WithMany("ReimbursementEntityRCAContacts")
                        .HasForeignKey("ReimbursementEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RCAContact");

                    b.Navigation("ReimbursementEntity");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.StudyContact", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Study", "Study")
                        .WithMany("StudyContacts")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.StudyHeader", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Study", null)
                        .WithMany("StudyHeaders")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.StudyHistology", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Histology", "Histology")
                        .WithMany("StudyHistologies")
                        .HasForeignKey("HistologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Study", "Study")
                        .WithMany("StudyHistologies")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Histology");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.StudyLookup", b =>
                {
                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Lookup", "Lookup")
                        .WithMany("StudyLookups")
                        .HasForeignKey("LookupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RCA_StudyManagementSystem.Shared.Domain.Study", "Study")
                        .WithMany("StudyLookups")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lookup");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Batch", b =>
                {
                    b.Navigation("PathReportExports");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Histology", b =>
                {
                    b.Navigation("StudyHistologies");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Hospital", b =>
                {
                    b.Navigation("DailyPathSubmissions");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Lookup", b =>
                {
                    b.Navigation("StudyLookups");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.PathReport", b =>
                {
                    b.Navigation("PathReportExports");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Patient", b =>
                {
                    b.Navigation("PathReports");

                    b.Navigation("PatientPhoneNumbers");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.RCAContact", b =>
                {
                    b.Navigation("ReimbursementEntityRCAContacts");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.ReimbursementEntity", b =>
                {
                    b.Navigation("ReimbursementEntityRCAContacts");
                });

            modelBuilder.Entity("RCA_StudyManagementSystem.Shared.Domain.Study", b =>
                {
                    b.Navigation("PatientStatuses");

                    b.Navigation("StudyContacts");

                    b.Navigation("StudyHeaders");

                    b.Navigation("StudyHistologies");

                    b.Navigation("StudyLookups");
                });
#pragma warning restore 612, 618
        }
    }
}
